### PR TITLE
Use erase-remove idiom to clean ':'

### PR DESCRIPTION
**Pull request by rbuch**

### CODE REVIEW

**Comment by mprobson** [comment]
I just ran this using our previous test data and got the following results:
```
$ time ./uneek file1.nsort.sam file2.nsort.sam > /dev/null 

real    19m45.107s
user    14m12.079s
sys     1m19.765s
```

Since this seems to slow down the program I'm not going to merge it but I'll re-run to confirm these numbers.

**Comment by mprobson** [comment]
I re-ran it and got the following timing results:
```
$ time ./uneek file1.nsort.sam file2.nsort.sam > /dev/null

real    19m37.845s
user    13m49.123s
sys     1m25.638s
```

**Comment by rbuch** [comment]
Yeah, the results I got on my laptop were also slightly slower, but I didn't expect that much of a slow down.  I'm fine abandoning this, I mostly did it for code cleanup.

Although, I'm a bit surprised that it's slower at all, I'd think it'd prevent quadratic search and remove behavior, but there may be something about the execution that I'm missing.

**Comment by mprobson** [comment]
I thought about this and re-ran the "optimized" version (without this change) and got the following performance:
```
time ./uneek file1.nsort.sam file2.nsort.sam > /dev/null 

real    19m40.305s
user    14m14.780s
sys     1m26.183s
```

**Comment by mprobson** [comment]
Looking at timing it seems basically the same so I'm going to merge it.

**Pull request merged**
